name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:24.0.7
        options: >-
          --privileged
          --entrypoint ""
        ports:
          - 8501:8501

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 src/ || true

    - name: Build Docker image
      run: docker compose build

    # Optional: Run a simple container test
    - name: Run Streamlit container for test
      run: |
        docker compose up -d
        sleep 10
        curl --fail http://localhost:8501 || exit 1

    - name: Shut down containers
      if: always()
      run: docker compose down
